name: 打包React-native安卓环境

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t rn_image .

      - name: Run in Docker container
        run: |
          docker run --name my_rn_container rn_image sh start.sh

      - name: Copy Apk
        run: |
          docker cp my_rn_container:/app/react-native-project/h5pack-native/android/app/build/outputs/apk/release/app-release.apk /home/runner/work/react-native-ci/react-native-ci/app.apk

      - name: Upload APK to Existing Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/Jimmylxue/react-native-ci/releases/192439895/assets?name=${{ github.run_number }}-${{ github.run_id }}.apk
          asset_path: /home/runner/work/react-native-ci/react-native-ci/app.apk
          asset_name: ${{ github.run_number }}-${{ github.run_id }}.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
