name: 打包React-native安卓环境

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@v2

      - name: 缓存 Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build --cache-from=type=local,src=/tmp/.buildx-cache -t rn_image .

      - name: Run in Docker container
        run: |
          docker run --name my_rn_container rn_image sh start.sh

      - name: List running containers
        run: |
          docker ps -a

      - name: Copy Apk
        run: |
          docker cp my_rn_container:/app/react-native-project/h5pack-native/app-release.apk /home/runner/work/react-native-ci/react-native-ci/app.apk

      - name: check pwd
        run: |
          pwd

      - name: check Apk
        run: |
          cd /home/runner/work/react-native-ci/react-native-ci

      - name: check Apk2
        run: |
          ls

      - name: Upload APK to Existing Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/Jimmylxue/react-native-ci/releases/192439895/assets?name=app.apk
          asset_path: /home/runner/work/react-native-ci/react-native-ci/app.apk
          asset_name: app.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
